name: Generate and Deploy Reports

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run daily script
        run: |
          python .github/scripts/daily.py

      - name: List dist directory
        run: ls -R dist

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git --branch gh-pages --single-branch gh-pages
          cp -r dist/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy reports"
          git push
